# Generated by Django 3.2.9 on 2022-03-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('inicio', models.TimeField(verbose_name='Entrada')),
                ('fin', models.TimeField(blank=True, null=True, verbose_name='Salida')),
                ('horas', models.SmallIntegerField(null=True, verbose_name='Horas')),
                ('minutos', models.SmallIntegerField(null=True, verbose_name='Horas')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.empleado')),
            ],
        ),
    ]
